package ru.itmo.eduassistant.bot.enm

enum class CallbackType {
    TEACHER_IN_MAIN_MENU_STATE_QUESTION_CHOICE,
    TEACHER_IN_QUEUE_MENU_STATE_QUEUE_CHOICE,
    TEACHER_IN_CREATING_QUEUE_STATE_CHANNEL_CHOICE,
    TEACHER_IN_CHANNEL_MENU_STATE_CHANNEL_CHOICE,

    STUDENT_IN_MAIN_MENU_STATE_CHANNEL_CHOICE,
    STUDENT_IN_MAIN_MENU_STATE_QUEUE_CHOICE,
    STUDENT_IN_CHANNEL_MENU_STATE_CHANNEL_CHOICE,
    STUDENT_IN_QUESTION_MENU_STATE_QUESTION_CHOICE,
    STUDENT_IN_QUESTION_MENU_STATE_CHANNEL_CHOICE
}