package ru.itmo.eduassistant.bot.enm

enum class DataType {
    TEACHER_IN_CREATING_QUEUE_STATE_QUEUE_NAME,
    TEACHER_IN_CREATING_QUESTION_CHAIN_MESSAGE_STATE_CURRENT_QUESTION_ID,
    TEACHER_IN_CHANNEL_VIEW_STATE_CURRENT_CHANNEL_ID,
    TEACHER_IN_QUESTION_VIEW_STATE_CURRENT_QUESTION_ID,
    TEACHER_IN_QUEUE_VIEW_STATE_CURRENT_QUEUE_ID,

    STUDENT_IN_CHANNEL_VIEW_CURRENT_CHANNEL_ID,
    STUDENT_IN_QUESTION_VIEW_STATE_CURRENT_QUESTION_ID,
    STUDENT_IN_QUEUE_VIEW_STATE_CURRENT_QUEUE_ID,
    STUDENT_IN_CREATING_QUESTION_VIEW_CURRENT_CHANNEL_ID
}