spring:
  application:
    name: EduAssistantBackend
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
server:
  port: 8080